### ISSUE TITLE
Get Odoo Client Error when deleting a  sheet.

### ISSUE THREAD

**Issue by caojm** [OCA/spreadsheet#17]
## Module
spreadsheet_oca

## Describe the bug
Get Odoo Client Error when deleting a  sheet. 
Details of the error are as follows:
UncaughtPromiseError > TypeError
Uncaught Promise > env.askConfirmation is not a function

TypeError: env.askConfirmation is not a function
    at Proxy.action (http://192.168.56.55:8169/web/assets/432-b2d3786/spreadsheet.o_spreadsheet.min.js:949:197)
    at Menu.activateMenu (http://192.168.56.55:8169/web/assets/432-b2d3786/spreadsheet.o_spreadsheet.min.js:697:60)
    at Menu.onClickMenu (http://192.168.56.55:8169/web/assets/432-b2d3786/spreadsheet.o_spreadsheet.min.js:713:11)
    at Menu.hdlr5 (eval at compile (http://192.168.56.55:8169/web/assets/425-76b1f63/web.assets_common.min.js:2051:370), <anonymous>:50:27)
    at Object.mainEventHandler (http://192.168.56.55:8169/web/assets/425-76b1f63/web.assets_common.min.js:2096:77)
    at HTMLDivElement.listener (http://192.168.56.55:8169/web/assets/425-76b1f63/web.assets_common.min.js:1292:15)
## To Reproduce
![图片](https://github.com/OCA/spreadsheet/assets/20367653/3d61b0e2-0d24-4965-b831-375b851ef091)

**Additional context**
odoo is deployed on debian11.

**Comment by chrisandrewmann** [comment]
Just received this error myself, still happening on V16 with latest updates and current spreadsheet_oca (16.0.1.2.3) and spreadsheet_dashboard_oca (16.0.1.1.0)
