### ISSUE TITLE
Get Odoo Client Error when clicking on "Data" tab.

### ISSUE THREAD

**Issue by MariaBForgeFlow** [OCA/spreadsheet#23]
## Module
spreadsheet_oca

## Describe the bug
Get Odoo Client Error when clicking on "Data" tab.

**Details of the error:**
UncaughtPromiseError > OwlError
Uncaught Promise > Got duplicate key in t-foreach: refresh_all_data

OwlError: Got duplicate key in t-foreach: refresh_all_data
    at Menu.slot1 (eval at compile ((http://localhost:8069/web/assets/debug/web.assets_common.js:21943:20), <anonymous>:37:44))
    at callSlot (http://localhost:8069/web/assets/debug/web.assets_common.js:19362:37) 
    at Popover.slot1 (eval at compile (http://localhost:8069/web/assets/debug/web.assets_common.js:21943:20), <anonymous>:14:16)
    at callSlot (http://localhost:8069/web/assets/debug/web.assets_common.js:19362:37) 
    at Portal.template (http://localhost:8069/web/assets/debug/web.assets_common.js:19162:50) 
    at Fiber._render (http://localhost:8069/web/assets/debug/web.assets_common.js:18116:38) 
    at Fiber.render (http://localhost:8069/web/assets/debug/web.assets_common.js:18108:18) 
    at ComponentNode.initiateRender (http://localhost:8069/web/assets/debug/web.assets_common.js:18772:23) 

## To Reproduce
**Affected versions**: 16.0.1.2.0

**Steps to reproduce the behavior:**
![image](https://github.com/OCA/spreadsheet/assets/146103561/ffa8da43-ca85-455a-a982-1323dbc67af9)

**Comment by Cippoco** [comment]
Dear Maria, did you find what was wrong? I've a similar problem in a custom module...

**Comment by Cippoco** [comment]
> Dear Maria, did you find what was wrong? I've a similar problem in a custom module...

I've found the solution to my issue, odoo had duplicate a server action so it fail in the t-foreach, under technical setting > server action, search for the action name and delete it.

**Comment by legalsylvain** [comment]
Hi. @MariaBForgeFlow. Is it possible to reproduce the bug on runboat ?
