### ISSUE TITLE
Cannot find odoo_line in this registry!    when edit line graph 

### ISSUE THREAD

**Issue by jeffery9** [OCA/spreadsheet#9]
## Module
The name of the module that has a bug.

## Describe the bug

OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (http://test.geninit.cn:9002/web/assets/debug/web.assets_common.js:16174:35) (/web/static/lib/owl/owl.js:124)
    at owl.App.handleError (http://test.geninit.cn:9002/web/assets/debug/web.assets_common.js:21777:20) (/web/static/lib/owl/owl.js:5727)
    at Fiber._render (http://test.geninit.cn:9002/web/assets/debug/web.assets_common.js:17674:30) (/web/static/lib/owl/owl.js:1624)
    at Fiber.render (http://test.geninit.cn:9002/web/assets/debug/web.assets_common.js:17663:18) (/web/static/lib/owl/owl.js:1613)
    at ComponentNode.initiateRender (http://test.geninit.cn:9002/web/assets/debug/web.assets_common.js:18402:23) (/web/static/lib/owl/owl.js:2352)

Caused by: Error: Cannot find odoo_line in this registry!
    at Registry.get (http://test.geninit.cn:9002/web/assets/debug/spreadsheet.o_spreadsheet.js:2777:27) (/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js:2772)
    at get chartPanel [as chartPanel] (http://test.geninit.cn:9002/web/assets/debug/spreadsheet.o_spreadsheet.js:8888:64) (/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js:8883)
    at ChartPanel.template (eval at compile (http://test.geninit.cn:9002/web/assets/debug/web.assets_common.js:21532:16), <anonymous>:46:24) (/web/static/lib/owl/owl.js:5482)
    at Fiber._render (http://test.geninit.cn:9002/web/assets/debug/web.assets_common.js:17671:38) (/web/static/lib/owl/owl.js:1621)
    at Fiber.render (http://test.geninit.cn:9002/web/assets/debug/web.assets_common.js:17663:18) (/web/static/lib/owl/owl.js:1613)
    at ComponentNode.initiateRender (http://test.geninit.cn:9002/web/assets/debug/web.assets_common.js:18402:23) (/web/static/lib/owl/owl.js:2352)

## To Reproduce
**Affected versions**:
16.0

1. go to dashboard settings, select sales and click edit button
2. in spreadsheet, select line graph and click edit
3.

**Expected behavior**

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by coolbirdzik** [comment]
Same on me

**Comment by etobella** [comment]
Added a PR fixing the issue.

Thanks for reporting it
